baseURL = "https://localhost:1313/"
title = "Radio Weesper"
theme = "radio-weesper-theme"

[params]
radio_online = true
# Additional custom parameters can be added here
# Separator used between title and suffix (outlined sparkle by default)
separator = "✧"

[outputs]
	section = ["HTML", "JSON"]

[menu]
	[[menu.main]]
		name = "Home"
		url = "/"
		weight = 1

	[[menu.main]]
		name = "Artists"
		url = "/artist/"
		weight = 2

	[[menu.main]]
		name = "Archive"
		url = "/archive/"
		weight = 3

	[[menu.main]]
		name = "Schedule"
		url = "/schedule/"
		weight = 4

	[[menu.main]]
		name = "Search"
		url = "/search/"
		weight = 5
