baseURL = "https://localhost:1313/"
title = "Radio Weesper"
theme = "radio-weesper-theme"

[params]
radio_online = false
# Additional custom parameters can be added here

[outputs]
	section = ["HTML", "JSON"]

[menu]
	[[menu.main]]
		name = "Home"
		url = "/"
		weight = 1

	[[menu.main]]
		name = "Archive"
		url = "/archive/"
		weight = 2

	[[menu.main]]
		name = "Schedule"
		url = "/schedule/"
		weight = 3	
	[[menu.main]]
		name = "Search"
		url = "/search/"
		weight = 4	
