
baseURL = "https://localhost:1313/"
title = "Radio Weesper"
theme = "radio-weesper-theme"

[params]
radio_online = false
# Additional custom parameters can be added here

[menu]
	[[menu.main]]
		name = "Home"
		url = "/"
		weight = 1

	[[menu.main]]
		name = "Archive"
		url = "/archive/"
		weight = 2
